In [5]:
import pandas as pd
import numpy as np

In [6]:
dataset = {
    'Name': ['Keshav', 'Anuj', 'Prathamesh', 'Adinath', 'Aditya', 'Harsh', 'Shreyas', 'Tejas'],
    'Math': [122, 78, 86, 84, 10, 68, 78, np.nan],
    'Science': [np.nan, 45, 87, 65, 85, 255, 10, 87],
    'CGPA': [120, np.nan, 8, 8.87, 7.65, 5.59, 8.45, 9.84]
}

df = pd.DataFrame(dataset)
df

         Name   Math  Science    CGPA
0      Keshav  122.0      NaN  120.00
1        Anuj   78.0     45.0     NaN
2  Prathamesh   86.0     87.0    8.00
3     Adinath   84.0     65.0    8.87
4      Aditya   10.0     85.0    7.65
5       Harsh   68.0    255.0    5.59
6     Shreyas   78.0     10.0    8.45
7       Tejas    NaN     87.0    9.84

In [7]:
df.isnull().sum()

Name       0
Math       1
Science    1
CGPA       1
dtype: int64

In [8]:
df.loc[df['Math'] > 100, 'Math'] = 100
df.loc[df['Science'] > 100, 'Science'] = 100
df.loc[df['CGPA'] > 10, 'CGPA'] = 10

df

         Name   Math  Science   CGPA
0      Keshav  100.0      NaN  10.00
1        Anuj   78.0     45.0    NaN
2  Prathamesh   86.0     87.0   8.00
3     Adinath   84.0     65.0   8.87
4      Aditya   10.0     85.0   7.65
5       Harsh   68.0    100.0   5.59
6     Shreyas   78.0     10.0   8.45
7       Tejas    NaN     87.0   9.84

In [9]:
df['Math'] = df['Math'].fillna(df['Math'].mean())
df['Science'] = df['Science'].fillna(df['Science'].mean())
df['CGPA'] = df['CGPA'].fillna(df['CGPA'].mean())

df

         Name   Math     Science       CGPA
0      Keshav  100.0   68.428571  10.000000
1        Anuj   78.0   45.000000   8.342857
2  Prathamesh   86.0   87.000000   8.000000
3     Adinath   84.0   65.000000   8.870000
4      Aditya   10.0   85.000000   7.650000
5       Harsh   68.0  100.000000   5.590000
6     Shreyas   78.0   10.000000   8.450000
7       Tejas   72.0   87.000000   9.840000

In [10]:
Q1 = df['Math'].quantile(0.25)
Q3 = df['Math'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print('Lower: ', lower)
print('Upper: ', upper)

Lower:  50.75
Upper:  104.75

In [11]:
df = df[(df['Math'] >= lower) & (df['Math'] < upper)]
df

         Name   Math     Science       CGPA
0      Keshav  100.0   68.428571  10.000000
1        Anuj   78.0   45.000000   8.342857
2  Prathamesh   86.0   87.000000   8.000000
3     Adinath   84.0   65.000000   8.870000
5       Harsh   68.0  100.000000   5.590000
6     Shreyas   78.0   10.000000   8.450000
7       Tejas   72.0   87.000000   9.840000

In [12]:
Q1 = df['Science'].quantile(0.25)
Q3 = df['Science'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print('Lower: ', lower)
print('Upper: ', upper)

df = df[(df['Science'] >= lower) & (df['Science'] < upper)]
df

Lower:  7.0
Upper:  135.0

         Name   Math     Science       CGPA
0      Keshav  100.0   68.428571  10.000000
1        Anuj   78.0   45.000000   8.342857
2  Prathamesh   86.0   87.000000   8.000000
3     Adinath   84.0   65.000000   8.870000
5       Harsh   68.0  100.000000   5.590000
6     Shreyas   78.0   10.000000   8.450000
7       Tejas   72.0   87.000000   9.840000

In [13]:
Q1 = df['CGPA'].quantile(0.25)
Q3 = df['CGPA'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print('Lower: ', lower)
print('Upper: ', upper)

df = df[(df['CGPA'] >= lower) & (df['CGPA'] < upper)]
df

Lower:  6.396071428571426
Upper:  11.130357142857145

         Name   Math    Science       CGPA
0      Keshav  100.0  68.428571  10.000000
1        Anuj   78.0  45.000000   8.342857
2  Prathamesh   86.0  87.000000   8.000000
3     Adinath   84.0  65.000000   8.870000
6     Shreyas   78.0  10.000000   8.450000
7       Tejas   72.0  87.000000   9.840000

In [15]:
df['Normalize_Math'] = (df['Math'] - df['Math'].min())/(df['Math'].max() - df['Math'].min())
df['Normalize_Science'] = (df['Science'] - df['Science'].min())/(df['Science'].max() - df['Science'].min())
df['Normalize_CGPA'] = (df['CGPA'] - df['CGPA'].min())/(df['CGPA'].max() - df['CGPA'].min())

C:\Users\Keshav Kalani\AppData\Local\Temp\ipykernel_12976\764976880.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Normalize_Math'] = (df['Math'] - df['Math'].min())/(df['Math'].max() - df['Math'].min())
C:\Users\Keshav Kalani\AppData\Local\Temp\ipykernel_12976\764976880.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Normalize_Science'] = (df['Science'] - df['Science'].min())/(df['Science'].max() - df['Science'].min())
C:\Users\Keshav Kalani\AppData\Local\Temp\ipykernel_12976\764976880.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Normalize_CGPA'] = (df['CGPA'] - df['CGPA'].min())/(df['CGPA'].max() - df['CGPA'].min())

In [16]:
df

,Name,Math,Science,CGPA,Normalize_Math,Normalize_Science,Normalize_CGPA
0,Keshav,100.0,68.428571,10.000000,1.000000,0.758813,1.000000
1,Anuj,78.0,45.000000,8.342857,0.214286,0.454545,0.171429
2,Prathamesh,86.0,87.000000,8.000000,0.500000,1.000000,0.000000
3,Adinath,84.0,65.000000,8.870000,0.428571,0.714286,0.435000
6,Shreyas,78.0,10.000000,8.450000,0.214286,0.000000,0.225000
7,Tejas,72.0,87.000000,9.840000,0.000000,1.000000,0.920000